# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee9e00fc70640d9065538c74279d0f2fb994728a60a96c83a56ee94a18634585d7160be75316e1ab6ae916273e25b695348cbd35ecc2c8fc0b4b244ca6cbbfc

test:
  secret_key_base: 718c532de6995eb596bc1e42e9270e03dc555a12f412d873026f2b42e0d319a94fb3baae404c0bd033068b91b1748fe48b9295d0100593babfd7e4fd420e8cf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
